version: '3.8'

services:
  pgsql-crud:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    container_name: pgsql-crud
    restart: always
    networks:
      - crud-network
    volumes:
      - ./docker/db:/var/lib/postgresql/data

  adminer-crud:
    image: adminer
    container_name: adminer-crud
    restart: always
    ports:
      - 8080:8080
    networks:
      - crud-network

  nest-crud:
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./docker/nest.Dockerfile
    ports:
      - 3001:3000
    command: yarn start:dev
    container_name: nest-crud
    restart: unless-stopped
    networks:
      - crud-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

networks:
  crud-network: